INSERT INTO 'Bestellung' (Rechnungsbetrag,Lieferdatum,Bestelldatum,Lieferstatus,Emailadresse,ZahlungsID) VALUES
('32.33','29.11.2021','26.11.2021','Geliefert','hendrik.schmitt@web.de','1'),
('09.70','19.11.2021','15.11.2021','Retoure','philip.lorenz@web.de','2'),
('15.00','12.11.2021','09.11.2021','In Zustellung','jens.schmalen@gmx.de','3'),
('39.90','11.11.2021','05.11.2021','Geliefert','max-mustermann@protonmail.com','4'),
('220.00','15.12.2021','09.12.2021','Auftragsverarbeitung','helga-maier@mail.de','5')