INSERT INTO 'Bewertung' (Bewertungstitel,Punkte,'Alter',Bewertungstext,Datum,Emailadresse,ProduktID) VALUES
('Super Shirt','5','40','Shirt sitzt super! Wirkt außerdem sehr hochwertig - auch nach dem ersten Waschgang','20.10.2021','max-mustermann@protonmail.com','1'),
('Sticker lösen sich schnell!','2','50','Sticker lösen sich leider bereits nach wenigen Tagen...nicht weiterzuempfehlen!','10.10.2021','jens.schmalen@gmx.de','3'),
('Vape dampft gut','4','60','Kann ich weiterempfehlen','30.09.2020','hendrik.schmitt@web.de','5'),
('Angelhaken wunderbar','5','64','Aller super!','26.09.2020','philip.lorenz@web.de','4'),
('Lampe hält, was sie verspricht, aaaaber..','4','68','...manchmal geht sie einfach aus. Muss dann aus- und wieder eingeschaltet werden','22.09.2020','helga-maier@mail.de','2')