INSERT INTO 'Kunde' (Emailadresse,Telefonnummer,Vorname,Nachname,Passwort,Postleitzahl,Strasse,Hausnummer,Adresszusatz) VALUES
('hendrik.schmitt@web.de','015219211922','Hendrik','Schmitt','32597832jlkbnrwejn124','06385','Eschenweg','12','a'),
('philip.lorenz@web.de','06920436149','Philip','Lorenz','3dfj7832jlkbnrwejn124','09217','Ringstrasse','16',''),
('jens.schmalen@gmx.de','030214802537','Jens','Schmalen','32579s32jlkbnrwejn124','97794','Burgstrasse','4',''),
('max-mustermann@protonmail.com','030214802538','Max','Mustermann','325sdhf2jlkbnrwejn124','49808','Fliederweg','42','a'),
('helga-maier@mail.de','080020033407','Helga','Maier','32597832jlkjrwesgjn124','73760','Nelkenweg','113','')