INSERT INTO 'Produkt' (Name,Beschreibungstext,Preis,Produktbild,AnbieterID) VALUES
('Sportshirt','Atmungsaktives Sportshirt','39.90','amazon-marketplace.com/shirt.png','3'),
('Lampe','Grosse Stehlampe. Geeignet für Wohnzimmer.','220.00','amazon-marketplace.com/lampe.png','2'),
('Fan-Sticker','Individuelle Fansticker. 20er Pack.','15.00','amazon-marketplace.com/ind-sticker.png','4'),
('Angelhaken - 3er Pack','Profi-Angelhaken','09.70','amazon-marketplace.com/haken3er.png','5'),
('Vape','','33.33','amazon-marketplace.com/vape.png','6')
