INSERT INTO 'Zahlungsmethode' (Zahlungsart,Inhabername,Emailadresse,IBAN,Kontoadresse,Kartennummer,CVV,Code) VALUES
('PayPal','Hendrik Schmitt','hendrik.schmitt@web.de','','hendrik.schmitt@web.de','','',''),
('SEPA','Philip Lorenz','philip.lorenz@web.de','GB33BUKB20201555555555','','','',''),
('Kreditkarte','Jens Schmalen','jens.schmalen@gmx.de','','','4012888888881881','543',''),
('Gutschein','Max Mustermann','max-mustermann@protonmail.com','','','','','AMP-FBJ1285F'),
('SEPA','Helga Maier','helga-maier@mail.de','GB33BUKB20201555553333','','','','')
